server:
  port: 8081
  servlet:
    context-path: /covido/newcases
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/covido?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: welcome1
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect