server:
  port: 8081
  servlet:
    context-path: /covido/newcases
spring:
  datasource:
    url: jdbc:h2:mem:mydb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: sa
    password: password
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
